### ISSUE TITLE
(node:2280) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'shift' of undefined

### ISSUE THREAD

**Issue by MelodicAlbuild** [hammertechnik/KappaOS#1]
**Describe the bug**
Speaks for itself, Line 66, Char 19

**Expected behavior**
Good Question

**Screenshots**
No

**Desktop (please complete the following information):**
 - Discord Version [e.g. 1.4.19 Update]
NO

**Smartphone (please complete the following information):**
 - Discord Version [e.g. 26.4.19 Update]
 - Version [e.g. 3.0.0]
Wtf

**Additional context**
COOKIES

**Comment by Hammer1279** [comment]
Problem has been Fixed, put the new code in from that section

**Comment by Hammer1279** [comment]
line 64 to 67
